version: "3.9"
services:
  df-aggregator:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    # The db folder/file will be saved on the host machine
    # wherever the docker-compose is brought up from.
    # volumes:
    #   - "./df-db:/df-aggregator/df-db"
    # Currently using default settings for all optional flags
    # but can set here and change the CMD in Dockerfile, if desired.
    # environment:
    #   PORT_NUMBER: 8080
